doggo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  FrontRight_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - FrontRightJoint1
      - FrontRightJoint2
      - FrontRightJoint3
    pid:  {p: 1.5, i: 2, d: 0}
  FrontLeft_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - FrontLeftJoint1
      - FrontLeftJoint2
      - FrontLeftJoint3
    pid:  {p: 1.5, i: 2, d: 0}
  BackRight_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - BackRightJoint1
      - BackRightJoint2
      - BackRightJoint3
    pid:  {p: 1.5, i: 2, d: 0}
  BackLeft_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - BackLeftJoint1
      - BackLeftJoint2
      - BackLeftJoint3
    pid:  {p: 1.5, i: 2, d: 0}
